WIP

diff --git a/.github/workflows/verify_install.yaml b/.github/workflows/verify_install.yaml
--- a/.github/workflows/verify_install.yaml
+++ b/.github/workflows/verify_install.yaml
@@ -1,67 +1,60 @@
-name: Verify Installation
+name: Verify TestPyPI Install
 
 on:
   workflow_dispatch:
 
 jobs:
-  build_package:
+  py36_install_centos8:
     runs-on: ubuntu-latest
+    container:
+      image: centos:8
     steps:
-    - uses: actions/checkout@v2
-    - uses: ./.github/actions/package_solarwinds_apm
-  py3.6_install_centos8:
-    needs: build_package
-    runs-on: ubuntu-latest
-    steps:
-    - name: Install and run test
-      working-directory: ./tests/docker/install
-      run: docker-compose run py3.6-install-centos8
-  py3.7_install_debian10:
-    needs: build_package
-    runs-on: ubuntu-latest
-    steps:
-    - name: Install and run test
-      working-directory: ./tests/docker/install
-      run: docker-compose run py3.7-install-debian10
-  py3.8_install_alpine3.13:
-    needs: build_package
-    runs-on: ubuntu-latest
-    steps:
-    - name: Install and run test
-      working-directory: ./tests/docker/install
-      run: docker-compose run py3.8-install-alpine3.13
-  py3.8_install_alpine3.14:
-    needs: build_package
-    runs-on: ubuntu-latest
-    steps:
-    - name: Install and run test
-      working-directory: ./tests/docker/install
-      run: docker-compose run py3.8-install-alpine3.14
-  py3.8_install_centos7:
-    needs: build_package
-    runs-on: ubuntu-latest
-    steps:
-    - name: Install and run test
-      working-directory: ./tests/docker/install
-      run: docker-compose run py3.8-install-centos7
-  py3.8_install_debian10:
-    needs: build_package
-    runs-on: ubuntu-latest
-    steps:
-    - name: Install and run test
-      working-directory: ./tests/docker/install
-      run: docker-compose run py3.8-install-debian10
-  py3.9_install_debian10:
-    needs: build_package
-    runs-on: ubuntu-latest
-    steps:
-    - name: Install and run test
-      working-directory: ./tests/docker/install
-      run: docker-compose run py3.9-install-debian10
-  py3.10_install_debian10:
-    needs: build_package
-    runs-on: ubuntu-latest
-    steps:
-    - name: Install and run test
-      working-directory: ./tests/docker/install
-      run: docker-compose run py3.10-install-debian10
+    - name: Install solarwinds-apm sdist (tar)
+      run: pip install --extra-index-url https://test.pypi.org/simple/ --dest sdist/ solarwinds-apm --no-binary solarwinds-apm
+    - name: Check sdist-installed agent startup
+      run: |
+        export SW_APM_DEBUG_LEVEL=6
+        export SW_APM_SERVICE_KEY=invalid-token-for-testing-1234567890:servicename
+        export TEST_EXP_LOG_MESSAGES=(
+        ">> SSL Reporter using host='apm.collector.cloud.solarwinds.com' port='443' log='' clientid='inva...7890:servicename' buf=1000 maxTransactions='200' flushMaxWaitTime='5000' eventsFlushInterval='2' maxRequestSizeBytes='3000000' proxy=''"
+        "Warning: There is an problem getting the API token authorized. Metrics and tracing for this agent are currently disabled. If you'd like to learn more about resolving this issue, please contact technicalsupport@solarwinds.com."
+        )
+        set +e
+        result=$(opentelemetry-instrument python -c 'from solarwinds_apm import version; print(version.__version__)' 2>startup.log)
+        logs_ok=true
+        for expected in "${TEST_EXP_LOG_MESSAGES[@]}"; do
+            grep -F "$expected" startup.log || logs_ok=false
+        done
+        if [ $logs_ok == false ]; then
+            echo "FAILED! Expected messages were not found in startup.log"
+            echo "-- startup.log content --"
+            cat startup.log
+            exit 1
+        fi
+        set -e
+        echo -e "Agent startup verified successfully.\n"
+    - name: Download solarwinds-apm bdist (wheel)
+      run: pip install --extra-index-url https://test.pypi.org/simple/ --dest bdist/ solarwinds-apm
+    - name: Check bdist-installed agent startup
+      run: |
+        export SW_APM_DEBUG_LEVEL=6
+        export SW_APM_SERVICE_KEY=invalid-token-for-testing-1234567890:servicename
+        export TEST_EXP_LOG_MESSAGES=(
+        ">> SSL Reporter using host='apm.collector.cloud.solarwinds.com' port='443' log='' clientid='inva...7890:servicename' buf=1000 maxTransactions='200' flushMaxWaitTime='5000' eventsFlushInterval='2' maxRequestSizeBytes='3000000' proxy=''"
+        "Warning: There is an problem getting the API token authorized. Metrics and tracing for this agent are currently disabled. If you'd like to learn more about resolving this issue, please contact technicalsupport@solarwinds.com."
+        )
+        set +e
+        result=$(opentelemetry-instrument python -c 'from solarwinds_apm import version; print(version.__version__)' 2>startup.log)
+        logs_ok=true
+        for expected in "${TEST_EXP_LOG_MESSAGES[@]}"; do
+            grep -F "$expected" startup.log || logs_ok=false
+        done
+        if [ $logs_ok == false ]; then
+            echo "FAILED! Expected messages were not found in startup.log"
+            echo "-- startup.log content --"
+            cat startup.log
+            exit 1
+        fi
+        set -e
+        echo -e "Agent startup verified successfully.\n"
+
